spring.main.web-application-type=servlet
server.port=8080

embabel.agent.shell.interactive.enabled=false
spring.shell.interactive.enabled=false
spring.shell.noninteractive.enabled=false

embabel.agent.platform.rest.process-status-enabled=true
embabel.agent.platform.rest.process-kill-enabled=true
embabel.agent.platform.rest.process-events-enabled=true
